### ISSUE TITLE
progressive Resize interferes with exisiting sampler in pytorch dataloader (batch_sampler)

### ISSUE THREAD

**Issue by souravdalai18** [warner-benjamin/fastxtend#16] opened 2023-09-10 17:49 UTC

**Comment by warner-benjamin** [comment] 2023-09-11 00:25
@souravdalai18 could you provide some more details and a minimal reproduction? `ProgressiveResize` doesn't apply until after the batch has been collated and has been transferred to the GPU.

**Comment by warner-benjamin** [comment] 2023-10-16 04:12
I added a preallocate flag to `ProgressiveResize` in 23c07b0 which might help with this issue.

Closing due to inability to replicate. Please reopen with details if the issue persists in the next fastxtend release.

**Closed as completed by warner-benjamin** 2023-10-16 04:12 UTC
