### ISSUE TITLE
TypeError When Using TensorAudio Batch Transforms

### ISSUE THREAD

**Issue by vishalbakshi** [warner-benjamin/fastxtend#23] opened 2024-05-05 21:08 UTC
First off, thanks for such an awesome library, I'm using it for the first time and really enjoying it.

I am running into a `TypeError` when using one of the TensorAudio batch transforms (`VolumeBatch`, `PitchShift`, `TimeStretch`, `PitchShiftOrTimeStretch`) when calling `auds.summary` where `auds` is the `DataBlock`. 

I am using fastxtend version `0.1.7` and fastai version `2.7.14` on Kaggle.

I have created a reproducible example [in this Kaggle Notebook](https://www.kaggle.com/code/vishalbakshi/typeerror-when-using-fastxtend-audio-batch-tfms#Failing-Example). I chose to use Kaggle so that I can easily incorporate an audio classification dataset in the example.

In short, when I run the following code in that notebook:

```python
auds = DataBlock(blocks = (AudioBlock, CategoryBlock),  
                 get_x = ColReader("filename", pref=path/"audio"/"audio"), 
                 splitter = ColSplitter(),
                 get_y = ColReader("category"),
                 batch_tfms = PitchShift())

auds.summary(df)
```

I get the error:

```python
TypeError: BatchRandTransform.__call__() missing 1 required positional argument: 'split_idx'
```
I don't get this error when using the different item transforms (`Flip`, `Roll`, `Volume`, etc.) I also tried using fastai's built-in `aug_transforms` and `RandomResizedCropGPU` as `batch_tfms` and while it obviously doesn't do anything to the TensorAudio, `auds.summary` runs without error.

I looked at the [source code for `PitchShift`](https://github.com/warner-benjamin/fastxtend/blob/e43c005344d54a3e13724e78db55b6f3bead0279/fastxtend/audio/augment.py#L424) and `split_idx` is defined at the top.

I also saw that there is an `audio_fixes` branch open so perhaps this is already a known issue. I'm not proficient at the internals of fastai, but am happy to help troubleshoot this issue if you can point me in a general direction of where to start looking. Or, perhaps I'm implementing it wrong and that's why I'm getting this error.

**Comment by warner-benjamin** [comment] 2024-05-06 05:33
I think the issue is probably due to `BatchRandTransform.__call__` not defaulting `split_idx=None`

Can you add this code right after the imports and see if it resolves the issue?

```python
from fastxtend.transform import BatchRandTransform

def call_fix(self,
    b:Tensor|tuple[Tensor,...], # Batch item(s)
    split_idx:int|None = None, # Train (0) or valid (1) index
    **kwargs
) -> Tensor|tuple[Tensor,...]:
    "Call `super().__call__` if `self.do`"
    self.before_call(b, split_idx=split_idx)
    return super().__call__(b, split_idx=split_idx, **kwargs) if self.do else b
    
BatchRandTransform.__call__ = call_fix
```

The audio_fixes branch was merged in #18. I forgot to delete it.

**Comment by vishalbakshi** [comment] 2024-05-06 12:50
Thanks that works!

This code:

```python
auds = DataBlock(blocks = (AudioBlock, CategoryBlock),  
                 get_x = ColReader("filename", pref=path/"audio"/"audio"), 
                 splitter = ColSplitter(),
                 get_y = ColReader("category"),
                 batch_tfms = PitchShift())

auds.summary(df)
```

Now outputs the expected result:

![image](https://github.com/warner-benjamin/fastxtend/assets/28925987/9be189d2-0df6-47db-8a84-f2eb5e13ee8a)




Note that I was running into the following error when using your fix:

![image](https://github.com/warner-benjamin/fastxtend/assets/28925987/9cbd3d01-02e3-46e4-93c0-423f86668c6c)

when running `auds.summary(df)`:

![image](https://github.com/warner-benjamin/fastxtend/assets/28925987/b839fa3e-58ef-4dda-9ed7-9131be0ca9ac)

So I modified the `return` statement as follows (ChatGPT assist) and it worked:

```python
def call_fix(self,
    b:Tensor|tuple[Tensor,...], # Batch item(s)
    split_idx:int|None = None, # Train (0) or valid (1) index
    **kwargs
) -> Tensor|tuple[Tensor,...]:
    "Call `super().__call__` if `self.do`"
    self.before_call(b, split_idx=split_idx)
    return super(BatchRandTransform, self).__call__(b, split_idx=split_idx, **kwargs) if self.do else b
    
BatchRandTransform.__call__ = call_fix
```

**Comment by warner-benjamin** [comment] 2024-05-06 19:56
@vishalbakshi can you check that #24 resolves this issue? If so, I will merge it and cut a release.

**Closed as completed** 2024-05-07 17:52 UTC
